import type { Metadata } from "next";
import {  Roboto } from "next/font/google";
import "./globals.css";
import Navigation from "@/ui/header/navigation";
import Footer from "@/ui/footer/main";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Weddin Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body
      >
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
